version: 2
jobs:
  build:
    docker:
    - image: circleci/node:latest
    steps:
    - checkout
    - restore_cache:
        keys:
        - v1-dependencies-{{ checksum "package.json" }}
        - v1-dependencies-
    - run:
      name: Install pacakges
      command: yarn
    - save_cache:
        paths:
        - node_modules/
        key: v1-dependencies-{{ checksum "package.json" }}
    - run:
      name: Run tests and upload to Codecov
      command: |
        yarn test
        yarn codecov
    - store_test_results:
        path: test/unit

workflows:
  version: 2
  build-and-test:
    jobs:
    - build
