version: 2
jobs:
  build:
    docker:
      - image: circleci/node:latest
    steps:
      - checkout
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          - v1-dependencies-
      - run: yarn global add codecov
      - run: yarn
      - save_cache:
          paths:
            - node_modules/
          key: v1-dependencies-{{ checksum "package.json" }}
      - run: yarn test
  test:
    docker:
      - image: circleci/node:latest
    steps:
      - checkout
      - run: yarn global add codecov
      - run: yarn
      - run: yarn test
      - store_test_results:
        path: test/unit

workflows:
  version: 2
    build_and_test:
      jobs:
        - build
        - test
